Add version compare check

diff --git a/.github/workflows/check-pr.yaml b/.github/workflows/check-pr.yaml
--- a/.github/workflows/check-pr.yaml
+++ b/.github/workflows/check-pr.yaml
@@ -47,6 +47,30 @@ jobs:
           if [[ ! "${{ needs.check-addon-changes.outputs.changedChangelogFiles }}" =~ "${{ matrix.addon }}/CHANGELOG.md" ]]; then
               echo "::error::No new entries in ${{ matrix.addon }} CHANGELOG.md file!"
               exit 1
+          fi
+
+  check-version-matching:
+    name: Check for same addon versions
+    if: ${{ needs.check-addon-changes.outputs.changedAddons != '[]' }}
+    runs-on: ubuntu-latest
+    needs: check-addon-changes
+    strategy:
+      fail-fast: false
+      matrix:
+        addon: ${{ fromJSON(needs.check-addon-changes.outputs.changedAddons) }}
+    steps:
+
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Check if versions of CHANGELOG.md and config.json match
+        shell: bash
+        run: |
+          config_version=$(sed -nr "s/.*version.*\"(.+)\".*/\1/p" "${{ matrix.addon }}/config.json")
+          changelog_version=$(sed -nr "0,/#{1,2}\s+(\S+)\s+-.*/{s//\1/p}" "${{ matrix.addon }}/CHANGELOG.md")
+          if [[ ! "$config_version" = "$changelog_version" ]]; then
+              echo "::error::The config version does not match the latest Changelog version!"
+              exit 1
           fi 
 
   check-build:
