Add label workflows

diff --git a/.github/workflows/check-pr.yaml b/.github/workflows/check-pr.yaml
--- a/.github/workflows/check-pr.yaml
+++ b/.github/workflows/check-pr.yaml
@@ -71,6 +71,29 @@ jobs:
           if [[ ! "$config_version" = "$changelog_version" ]]; then
               echo "::error::The config version does not match the latest Changelog version!"
               exit 1
+          fi
+
+  check-addon-label:
+    name: Check for existance of the addon label
+    if: ${{ needs.check-addon-changes.outputs.changedAddons != '[]' }}
+    runs-on: ubuntu-latest
+    needs: check-addon-changes
+    strategy:
+      fail-fast: false
+      matrix:
+        addon: ${{ fromJSON(needs.check-addon-changes.outputs.changedAddons) }}
+    steps:
+
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Check if a label for the addon exists
+        shell: bash
+        run: |
+          labeltext=$(sed -nr "s/name:\s(${{ matrix.addon }}).*/\1/p" '.github/labels.yaml')
+          if [[ -z "$labeltext" ]]; then
+              echo "::error::There is no label for this addon! Please add it to .github/labels.yaml and .github/labeler.yaml"
+              exit 1
           fi 
 
   check-build:
