Check also images existing on PR

diff --git a/.github/workflows/check-pr.yml b/.github/workflows/check-pr.yml
--- a/.github/workflows/check-pr.yml
+++ b/.github/workflows/check-pr.yml
@@ -95,3 +95,21 @@ jobs:
           -d ${{ steps.config.outputs.registry }} 
           -i ${{ steps.config.outputs.imagetemplate }}
           --test
+
+      - name: Check images
+        if: steps.files-check.outputs.changed == 'true'
+        shell: bash
+        run: |
+          missing=0
+          for image_name in ${{ steps.config.outputs.image_names }}; do
+            if [[ "$(docker images -q "$image_name:${{ steps.config.outputs.version }}" 2> /dev/null)" == "" ]]; then
+              echo "::error::No local image for $image_name found."
+              missing=$((missing + 1))
+            else
+              echo "Image $image_name found."
+            fi
+          done
+          if [ "$missing" -gt "0" ]; then
+            docker images
+            exit 1
+          fi
