Add Changelog change check

diff --git a/.github/workflows/check-pr.yaml b/.github/workflows/check-pr.yaml
--- a/.github/workflows/check-pr.yaml
+++ b/.github/workflows/check-pr.yaml
@@ -9,16 +9,43 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       changedAddons: ${{ steps.filter.outputs.changes }}
+      changedChangelogFiles: ${{ steps.changed-files.outputs.changelogs_files }}
     steps:
 
     - name: Checkout
       uses: actions/checkout@v2
 
-    - name: Detect chanced files
+    - name: Detect chanced addons
       uses: dorny/paths-filter@v2
       id: filter
       with:
         filters: .github/paths-filter.yml
+
+    - name: Detect chanced files
+      uses: dorny/paths-filter@v2
+      id: changed-files
+      with:
+        list-files: csv
+        filters: |
+          changelogs:
+            - '**/CHANGELOG.md'
+
+  check-changed-changelog:
+    name: Check if CHANGELOG.md changed
+    runs-on: ubuntu-latest
+    needs: check-addon-changes
+    strategy:
+      matrix:
+        addon: ${{ fromJSON(needs.check-addon-changes.outputs.changedAddons) }}
+    steps:
+
+      - name: Check for updated CHANGELOG.md
+        shell: bash
+        run: |
+          if [[ ! "${{ needs.check-addon-changes.outputs.changedChangelogFiles }}" =~ "${{ matrix.addon }}/CHANGELOG.md" ]]; then
+              echo "::error::No new entries in ${{ matrix.addon }} CHANGELOG.md file!"
+              exit 1
+          fi 
 
   check-build:
     name: Check build
