Fix versioncheck glob

diff --git a/.github/workflows/lint-checks.yaml b/.github/workflows/lint-checks.yaml
--- a/.github/workflows/lint-checks.yaml
+++ b/.github/workflows/lint-checks.yaml
@@ -75,14 +75,20 @@ jobs:
         with:
           list-files: 'shell'
           filters: |
-            config:
-              - '**/[!.]*'
+            changed:
+              - '**/*'
 
       - name: Check if version of changed addon is changed also
-        if: steps.filter.outputs.shell == 'true'
+        if: steps.filter.outputs.changed == 'true'
         run: |
-          for file in "${{ steps.filter.outputs.config_files }}"
+          for file in "${{ steps.filter.outputs.changed_files }}"
           do
             addon_folder=$(dirname $file)
-            git diff "$addon_folder/config.json" | grep -P '\+.+"version".+'
+            if [ -f "$addon_folder/config.json" ]; then
+              git diff master -- "$addon_folder/config.json" | grep -P '\+.+"version".+'
+              if [ $? -ne 0 ]; then
+                  echo "::error::$addon_folder didn't change the addon version."
+                  exit 1
+              fi
+            fi
           done
