Add entrypoint test

diff --git a/.github/workflows/master-push.yaml b/.github/workflows/master-push.yaml
--- a/.github/workflows/master-push.yaml
+++ b/.github/workflows/master-push.yaml
@@ -104,6 +104,14 @@ jobs:
               missing=$((missing + 1))
             else
               echo "Image $image_name found."
+
+              entrypoint=$(docker inspect "$image_name:${{ steps.config.outputs.version }}" | jq --raw-output '.[].Config.Entrypoint[]')
+              cmd=$(docker inspect "$image_name:${{ steps.config.outputs.version }}" | jq --raw-output '.[].Config.Cmd[]')
+              if [ -n "$cmd" ] || ([ "$entrypoint" != "/init" ] && [ "$entrypoint" != "/run" ]); then
+                echo "::error::Invalid docker entrypoint found"
+                exit 1
+              fi
+              
             fi
           done
           if [ "$missing" -gt "0" ]; then
